version: "3.5"
services:
  frontend:
    image: okaufmann/expose-docker:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: "expose serve your-domain.com"
    volumes:
      - ./.data/expose.db:/root/.expose/expose.db
    environment:
      - VALIDATE_AUTH_TOKENS=true
      - DASHBOARD_USER=admin
      - DASHBOARD_PASSWORD=secret